print("Olá, ")
print("Meu nome é Danielle, ")
print("Tenho 38 anos, ")
print("Faço faculdade de análise e desenvolvimento de sistema, ")
print("Trabalho na Motorola, ")
print("Solteira, ")
print("Tenho 2 irmãos e 2 sobrinhas, ")
print("Moro com meu pai, ")
print("Namoro a Vanessa. ")
print()